REGION_NAME = 'us-west-2'  # Oregon
KEYPAIR_NAME = 'chefswap'  # predefined
INSTANCE_TYPE = 't2.micro'
AMI_ID = "ami-5324402b"
SECRET_KEY = "VRUkBl6P25PBqU6OP3KgNAzaci6HbFAaCfbPrHU/"
ACCESS_KEY_ID = 'AKIAIMC3TJ4C5HEHZNIA'

NUM_CPUS = 8
MAX_USERS = 40000

MAXCOUNT_INSTANCE = 20
NUM_SLAVES = 2
COMMAND_TIME_OUT = 120