REGION_NAME = 'us-west-2'  # Oregon
KEYPAIR_NAME = 'tsung'  # predefined
KAFKA_INSTANCE_TYPE = 't2.large'
ZOO_INSTANCE_TYPE = 't2.large'
#AMI_ID = 'ami-bf4193c7'  #
AMI_ID = 'ami-c551e7bd'
SECRET_KEY = "7UwV1mdq2GnsmmiCT3IyRNwEC9HVBM1H/aGNtC25"
ACCESS_KEY_ID = 'AKIAITPGMMWLTOJVJRGA'

NUM_CPUS = 8
MAX_USERS = 40000

MAXCOUNT_INSTANCE = 20
NUM_SLAVES = 2
COMMAND_TIME_OUT = 120